services:
  keycloak-demo:
    image: quay.io/keycloak/keycloak:24.0.3
    command: start-dev #as we are not in production
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres_keycloak_demo #linked to the postgres service
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_SCHEMA: public
      #The env below are specific for the keycloak entrance console
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8090:8080"
    depends_on:
      postgres_keycloak_demo:
        condition: service_healthy
    networks:
      - keycloak_demo_dev_network
  postgres_keycloak_demo:
    image: postgres:14.2
    command: postgres -c 'max_connections=200'
    volumes:
      - pgdata_keycloak_demo:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    healthcheck:
      test: "exit 0"
    ports:
      - "5436:5432"
    networks:
      - keycloak_demo_dev_network
volumes: 
  pgdata_keycloak_demo:
networks:
  keycloak_demo_dev_network:
    driver: bridge