apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 8081 #accessible by other services within the same cluster
      targetPort: 8081 #any traffic received by the Service on "port" will be forwarded to target port, on the MongoDB Pod
      nodePort: 30007 #nodeport range from 30000 to 32000
