apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-gui
spec:
  selector:
    matchLabels:
      app: mongo-gui
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-gui
    spec:
      containers:
        - name: mongo-gui
          image: mongo-express
          ports:
            - containerPort: 8081
          env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-user
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-password
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: mongo-url


            