apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    app: node-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-server
  template:
    metadata:
      labels:
        app: node-server
    spec:
      containers:
      - name: node-container
        image: oscargomezgonzalezz/todo:1.0.0
        ports:
        - containerPort: 3500
        env:
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-secret-key
        - name: MONGO_URL
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-url
        

